events { 
    worker_connections 1024; 
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # 1. Раздача фронтенда
        location / {
            root /usr/share/nginx/html;
            index index.html;
            # Полезно для SPA: если файл не найден, отдаем index.html
            try_files $uri $uri/ /index.html; 
        }

        # 2. Проксирование API-запросов к ASP.NET Core
        location /api/ {
            # 'api' - это название контейнера бэкенда в docker-compose.prod.yml
            # Порт 80 или 8080 зависит от твоего Dockerfile API (в .NET 8 по умолчанию 8080)
            proxy_pass http://api:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}